on:
  schedule:
  - cron: '0 16 * * *'  # equivalent to '0 0 * * *' CST
name: Excavator
jobs:
  excavate:
    name: Excavator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@stable-win
      env:
        GITH_EMAIL: mattoncis@hotmail.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
